import { ArmyType } from '../models/Army';
import { army } from '../constants/enums';

export const mockArmy: ArmyType = {
  [army.soldier]: {
    id: army.soldier,
    title: 'Особовий склад',
    description: '',
    imgSrc: '/static/army/soldier.webp',
    count: 0,
    cost: 100,
    damage: 100,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:0.5,
      [army.tank]:0.1,
      [army.copter]:0,
      [army.bpla]:0,
      [army.plane]:0,
      [army.ship]:0,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 100,
    levelCostMultiplier: 2.5,
    hp:100,
  },
  [army.auto]: {
    id: army.auto,
    title: 'Автомобільна техніка',
    description: '',
    imgSrc: '/static/army/auto.webp',
    cost: 300,
    count: 0,
    damage: 200,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:0.7,
      [army.tank]:0.2,
      [army.copter]:0,
      [army.bpla]:0,
      [army.plane]:0,
      [army.ship]:0,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 200,
    levelCostMultiplier: 2.5,
    hp:200,
  },
  [army.tank]: {
    id: army.tank,
    title: 'Танки',
    description: '',
    imgSrc: '/static/army/tank.webp',
    cost: 500,
    count: 0,
    damage: 300,
    attackAbility: {
      [army.soldier]: 2,
      [army.auto]:1.5,
      [army.tank]:1,
      [army.copter]:0.2,
      [army.bpla]:0,
      [army.plane]:0,
      [army.ship]:0,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 300,
    levelCostMultiplier: 2.5,
    hp:300,
  },
  [army.copter]: {
    id: army.copter,
    title: 'Гелікоптери',
    description: '',
    imgSrc: '/static/army/copter.webp',
    cost: 1000,
    count: 0,
    damage: 400,
    attackAbility: {
      [army.soldier]: 3,
      [army.auto]:2,
      [army.tank]:1.2,
      [army.copter]:0.6,
      [army.bpla]:0.2,
      [army.plane]:0,
      [army.ship]:0.3,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 400,
    levelCostMultiplier: 2.5,
    hp:300,
  },
  [army.bpla]: {
    id: army.bpla,
    title: 'БПЛА',
    description: '',
    imgSrc: '/static/army/bpla.webp',
    cost: 2000,
    count: 0,
    damage: 500,
    attackAbility: {
      [army.soldier]: 3,
      [army.auto]:2,
      [army.tank]:1.2,
      [army.copter]:0.4,
      [army.bpla]:0.2,
      [army.plane]:0.2,
      [army.ship]:0.3,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 500,
    levelCostMultiplier: 2.5,
    hp:300,
  },
  [army.plane]: {
    id: army.plane,
    title: 'Літаки',
    description: '',
    imgSrc: '/static/army/plane.webp',
    cost: 3000,
    count: 0,
    damage: 600,
    attackAbility: {
      [army.soldier]: 5,
      [army.auto]:3,
      [army.tank]:2,
      [army.copter]:0.5,
      [army.bpla]:0.3,
      [army.plane]:0.4,
      [army.ship]:0.2,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 600,
    levelCostMultiplier: 2.5,
    hp:400,
  },
  [army.ship]: {
    id: army.ship,
    title: 'Кораблі',
    description: '',
    imgSrc: '/static/army/ship.webp',
    cost: 5000,
    count: 0,
    damage: 700,
    attackAbility: {
      [army.soldier]: 5,
      [army.auto]:3,
      [army.tank]:2,
      [army.copter]:0.8,
      [army.bpla]:0.5,
      [army.plane]:0.5,
      [army.ship]:0.5,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 700,
    levelCostMultiplier: 2.5,
    hp:500,
  },
};
