import { ArmyType } from '../models/Army';
import { army } from '../constants/enums';

export const mockArmy: ArmyType = {
  [army.soldier]: {
    id: army.soldier,
    title: 'зубастики',
    description: '',
    imgSrc: '/static/army/soldier.webp',
    count: 0,
    cost: 1000,
    damage: 100,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:0.5,
      [army.tank]:0.1,
      [army.copter]:0,
      [army.bpla]:0,
      [army.plane]:0,
      [army.ship]:0,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 100,
    levelCostMultiplier: 2.5,
    hp:100,
  },
  [army.auto]: {
    id: army.auto,
    title: 'Автомобільна техніка',
    description: '',
    imgSrc: '/static/army/auto.webp',
    cost: 3000,
    count: 0,
    damage: 200,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:0.7,
      [army.tank]:0.2,
      [army.copter]:0,
      [army.bpla]:0,
      [army.plane]:0,
      [army.ship]:0,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 200,
    levelCostMultiplier: 2.5,
    hp:150,
  },
  [army.tank]: {
    id: army.tank,
    title: 'Танки',
    description: '',
    imgSrc: '/static/army/tank.webp',
    cost: 5000,
    count: 0,
    damage: 300,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:1,
      [army.tank]:1,
      [army.copter]:0.2,
      [army.bpla]:0,
      [army.plane]:0,
      [army.ship]:0,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 300,
    levelCostMultiplier: 2.5,
    hp:200,
  },
  [army.copter]: {
    id: army.copter,
    title: 'Гелікоптери',
    description: '',
    imgSrc: '/static/army/copter.webp',
    cost: 10000,
    count: 0,
    damage: 400,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:1,
      [army.tank]:1,
      [army.copter]:1,
      [army.bpla]:0.2,
      [army.plane]:0.2,
      [army.ship]:0.2,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 400,
    levelCostMultiplier: 2.5,
    hp:250,
  },
  [army.bpla]: {
    id: army.bpla,
    title: 'БПЛА',
    description: '',
    imgSrc: '/static/army/bpla.webp',
    cost: 20000,
    count: 0,
    damage: 500,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:1,
      [army.tank]:1,
      [army.copter]:1,
      [army.bpla]:0.2,
      [army.plane]:0.2,
      [army.ship]:0.2,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 500,
    levelCostMultiplier: 2.5,
    hp:300,
  },
  [army.plane]: {
    id: army.plane,
    title: 'Літаки',
    description: '',
    imgSrc: '/static/army/plane.webp',
    cost: 30000,
    count: 0,
    damage: 600,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:1,
      [army.tank]:1,
      [army.copter]:1,
      [army.bpla]:1,
      [army.plane]:1,
      [army.ship]:0.2,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 600,
    levelCostMultiplier: 2.5,
    hp:350,
  },
  [army.ship]: {
    id: army.ship,
    title: 'Кораблі',
    description: '',
    imgSrc: '/static/army/ship.webp',
    cost: 50000,
    count: 0,
    damage: 700,
    attackAbility: {
      [army.soldier]: 1,
      [army.auto]:1,
      [army.tank]:1,
      [army.copter]:1,
      [army.bpla]:1,
      [army.plane]:1,
      [army.ship]:1,
    },
    level: 1,
    levelBonus: 0.25,
    levelCost: 700,
    levelCostMultiplier: 2.5,
    hp:400,
  },
};
